version: '3.1'

services:

  app:
    build:
      context: ./app
    container_name: app-node
    entrypoint: 'dockerize -wait tcp://db:3306 -timeout 40s node main.js'
    networks:
      - node-network
    # volumes:
    #   - ./app:/usr/src/app
    #   - ./app/node_modules:/usr/src/app/node_modules
    tty: true
    depends_on: 
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: db-mysql
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - node-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx-app
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - app

networks:
  node-network:
    driver: bridge
