const app = require("./db/app");

app();

// DONE: 1 UTILIZAR ENV
// DONE: 2 CRIAR CONEXÃO INICIAL AO BANCO
// DONE: 3 CRIAR TABELA AO INICIAR DOCKER COMPOSE
// DONE: 4 CRIAR UTIL QUE ADICIONAR INFORMAÇÕES A TABELA
// DONE: 5 UTILIZAR UTIL NA ROTA GET
// TODO: 6 EXIBIR OS NOMES CONFORME FOREM ADICIONADOS
// TODO: 7 ADICIONAR WAIT FOR IT ENTRE AS SERVICES DO DOCKER COMPOSE
// TODO: 8 ADICIONAR README
